### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by judos** [prometheus-net/docker_exporter#5]
Great exporter. Love to have the data on my dashboards.

Is there detailled explanation what the docker_container_restart_count metrics exactly counts?

I have a value of 39.17 on my dashboard, no I know the container failed and I fixed the issue, but does the value go down to 0 again?

**Comment by sandersaares** [comment]
There is no detailed docs, largely because many metrics are raw values that come from Docker and Docker does not always explain things thoroughly.

This particular value goes down whenever Docker decides to make it go down. In my experience, it does not go down without user action or Docker restart. It just stops increasing if the container stops restarting.

**Comment by sandersaares** [comment]
I'll close this for now but feel free to post a new issue if more questions remain.
